apps/home/urls.py
from . import views
from django.urls import path


app_name = 'home'


urlpatterns = [
    path('', views.home_view, name='home'),
    path('review/', views.ReviewCreateView.as_view(), name='review')
]

apps/services/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('service/detail/<slug>/', views.service_detail_view, name='service_detail'),
    path('product/detail/<slug>/', views.product_detail_view, name='product_detail'),
    
    
]

apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('detail/<slug>/', views.profile_detail_view, name='profile_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone as time
# Create your models here.

class Review(models.Model):
    """Model definition for Review."""

    # TODO: Define fields here
    image = models.ImageField(default='/testimonials/team.png', upload_to='testimonials/')
    name = models.CharField(default='', max_length=50)
    job_description = models.CharField(default='', max_length=50)
    review = models.TextField()
    published_date = models.DateTimeField(default=time.now)
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        """Meta definition for Review."""

        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    def __str__(self):
        """Unicode representation of Review."""
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('home:service_detail', kwargs={'slug': self.slug})

    def save(self):
        if not self.slug:
            self.slug = slugify(self.name + self.job_description)
        return super().save()

apps/services/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone as time

# Create your models here.
class Service(models.Model):
    """Model definition for Service."""

    # TODO: Define fields here
    
    name = models.CharField(default='', max_length=50)
    about = models.TextField()
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        """Meta definition for Service."""

        verbose_name = 'Service'
        verbose_name_plural = 'Services'

    def __str__(self):
        """Unicode representation of Service."""
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('home:service_detail', kwargs={'slug': self.slug})

    def save(self):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save()

# PRODUCT MODEL
class Product(models.Model):
    """Model definition for Product."""

    # TODO: Define fields here
    
    name = models.CharField(default='', max_length=50)
    weight = models.CharField(max_length=100, default='')
    network = models.CharField(max_length=100, default='')
    loc_tech = models.CharField(max_length=100, default='')
    accuracy_range = models.CharField(max_length=10, default='')
    features = models.ManyToManyField(Service, related_name='products')
    published_date = models.DateTimeField(default=time.now)
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        """Meta definition for Product."""

        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        """Unicode representation of Product."""
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('home:product_detail', kwargs={'slug': self.slug})    

    def save(self):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save()

apps/users/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    """Model definition for Profile."""

    # TODO: Define fields here
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='members/team.png', upload_to='members/')
    role = models.CharField(default='', max_length=50)
    mobile = models.IntegerField(default='+263 000 000 000' )
    whatsapp = models.IntegerField(default='+263 000 000 000')


    slug = models.SlugField(blank=True, unique=True)

    class Meta:
        """Meta definition for Profile."""

        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        """Unicode representation of Profile."""
        return self.user.username

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('users:profile_detail', kwargs={'slug': self.slug})    

    def save(self):
        if not self.slug:
            self.slug = slugify(self.user.username)
        return super().save()

apps/home/forms.py
from django import forms
from .models import Review



class ReviewForm(forms.ModelForm):
    """Form definition for Review."""

    class Meta:
        """Meta definition for Reviewform."""

        model = Review
        fields = ['image','name','job_description','review',]
        labels = {
            'image':''
        }
        
        def __init__(self, *args, **kwargs):
            super(ReviewForm, self).__init__(*args, **kwargs)

            self.fields['image'].widget.attrs['required'] = 'required'
            self.fields['name'].widget.attrs['required'] = 'required'
            self.fields['job_description'].widget.attrs['required'] = 'required'
            self.fields['review'].widget.attrs['required'] = 'required'
        

apps/home/views.py
from multiprocessing import get_context
from django.urls import reverse
from django.shortcuts import render , get_object_or_404
from apps.services.models import Service, Product
from apps.users.models import Profile
from .models import Review
from .forms import ReviewForm
from django.views.generic import CreateView
# Create your views here.




def home_view(request):
    template_name = 'home.html'
    services = Service.objects.all()
    products = Product.objects.all()
    members = Profile.objects.all()
    reviews = Review.objects.all()[:3]
    
    context = {
        'page_title':'home',
        'services':services,
        'products':products,
        'members':members,
        'reviews':reviews,
    }
    return render(request, template_name, context)

def send_email(request):
    pass


class ReviewCreateView(CreateView):
    model = Review
    template_name = "review.html"
    form_class = ReviewForm
    success_url = 'home:home'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'review us'
        return context

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home:home')
    

apps/services/views.py
from django.shortcuts import render , get_object_or_404
from .models import Service, Product

# Create your views here.


def service_detail_view(request, slug):
    template_name = 'service_detail.html'
    service = get_object_or_404(Service, slug=slug)
    
    context = {
        'page_title':service.name,
        'service':service,
    }
    
   
    return render(request, template_name, context) 

#product detail view
def product_detail_view(request, slug):
    template_name = 'product_detail.html'
    product = get_object_or_404(Product, slug=slug)
    
    context = {
        'page_title':'product_detail',
        'product': product,
        
    }
    return render(request, template_name, context)

apps/users/views.py
from django.shortcuts import render, get_object_or_404
from .models import Profile
# Create your views here.

def profile_detail_view(request, slug):
    member = get_object_or_404(Profile, slug=slug)
    template_name = 'profile_detail.html'
    context = {
        'member': member,
        'page_title': 'profile'
    }
    return render(request, template_name, context)

apps/home/templates/home.html
{% extends 'index.html' %}
{% load static %}



{% block content %}
{% include 'partials/banner.html' %}
<main class="container" id="services">
	<h1>our services</h1>
	<div class="row">
		
		{% for service in services %}
		<div class="service">
	
			{% if service.name == 'Mileage Statistics' %}
			<i class="fa-solid fa-road-circle-check"></i>	
			{% elif service.name == 'Vehicle Location' %}
			<i class="fa-solid fa-map-location-dot"></i>
			{% elif service.name == 'Vibration Alarm' %}
			<i class="fa-solid fa-car-on"></i>
			{% elif service.name == 'Acc Status' %}
			<i class="fa-solid fa-gauge-high"></i>
			{% elif service.name == 'Remote Control' %}
			<i class="fa-solid fa-satellite"></i>	
			{% else %}
			
			{% endif %}
				
				
			<h2>{{ service.name|title }}</h2>
			<p>{{ service.about|capfirst }}.</p>
		</div>
		{% endfor %}

	</div>
</main>

{% include 'partials/testimonials.html' %}
{% include 'partials/team.html' %}
{% include 'partials/about.html' %}
{% include 'partials/contact.html' %}


{% endblock content %}
    

apps/home/templates/review.html
{% extends 'index.html' %}



{% block content %}
<section class="contact" id="contact">
	<div class="contact-content">
        <div class="contact-form">
            <form method="post" enctype="multipart/form-data" action="" >
                {% csrf_token %}
                <h2>Review Us</h2>
                <div class="input-box">
                    
                    {% for field in form %}
                    <span>{{ field.label }}</span>
                    {{ field }}
                    {% endfor %}
        
                <div class="input-box">
                    <input type="submit" value="send">
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}
    

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<title>{{ site_name_short }} - {{ page_title }}</title>
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Allura&family=Josefin+Sans&family=Poppins:wght@200;300;400&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/e6dbc383de.js" crossorigin="anonymous"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
</head>

<body class="content">
	<!--nav bar-->
	{% include 'partials/nav.html' %}
	<!--nav end-->

	<!--banner-->
	
	<!--banner end-->

	<!--content-->
	
	{% block content %}
		
	{% endblock content %}
		
	<!--content end-->

	<!--footer bar-->
	{% include 'partials/footer.html' %}
	<!--footer end-->
</body>
</html>

templates/partials/about.html
{% load static %}   

<section class="section" id="about">
	<div class="about-container">
		<div class="content-section">
			<div class="title">
				<h1>About Us</h1>
			</div>
			<div class="about-content">
				<h3>Thank you for taking your time to review our company</h3>
				<p>{{ site_bio|capfirst }}</p>
				<div class="button">
					<a href="#contact">Contact Us</a>
				</div>
			</div>
			<div class="social">
				<a href="https://www.facebook.com/107274258794499/posts/1156982825232001/?substory_index=1156982825232001&app=fbl"><i class="fab fa-facebook-f"></i></a>
				<a href=""><i class="fab fa-twitter"></i></a>
				<a href=""><i class="fab fa-instagram"></i></a>
			</div>
		</div>
		<div class="image-section">
			<img src="{% static 'css/img/about.jpg' %}" alt="image">
		</div>
	</div>
</section>

templates/partials/banner.html
{% load static %}

<section class="banner">
	<div class="container">
		<div class="banner-content">
			
			<h1>{{ site_name_full|upper }}</h1>
			<span>{{ moto|title }}</span>
			<p>{{ site_about|capfirst }}</p>
			
			<a href="#about" class="btn-one">discover</a>
		</div>
	</div>

</section>

templates/partials/contact.html
{% load static %}

<section class="contact" id="contact">
	<div class="contact-content">
		<h2>Contact Us</h2>
		<p>We are looking forward to your message.</p>
	</div>
	<div class="contact-container">
		<div class="contact-info">
			<div class="box">
				<div class="icon">
					<i class="fa-solid fa-map-location-dot"></i>
				</div>
				<div class="text">
					<h3>Address</h3>
					<p>Available in zimbawe</p>
				</div>
			</div>
			<div class="box">
				<div class="icon">
					<i class="fa-solid fa-phone"></i>
				</div>
				<div class="text">
					<h3>Phone</h3>
					<p>+263 774 007 593</p>
					<p>+263 773 768 222</p>
				</div>
			</div>
			<div class="box">
				<div class="icon">
					<i class="fa-brands fa-whatsapp"></i>
				</div>
				<div class="text">
					<h3>Whatsapp</h3>
					<p>+8618351981380</p>
				</div>
			</div>
			<div class="box">
				<div class="icon">
					<i class="fa-solid fa-envelope"></i>
				</div>
				<div class="text">
					<h3>Email</h3>
					<p>info@ara.co.zw</p>
				</div>
			</div>
		</div>
		<div class="contact-form">
			<form action="">
				<h2>Send Message</h2>
				<div class="input-box">
					<input type="text" name="" required="required">
					<span>Full Name</span>
				</div>
				<div class="input-box">
					<input type="text" name="" required="required">
					<span>Email</span>
				</div>
				<div class="input-box">
					<textarea name="" id="" cols="30" rows="10" required="required"></textarea>
					<span>Message</span>
				</div>
				<div class="input-box">
					<input type="submit" value="send">
				</div>
			</form>
		</div>
	</div>
</section>   

templates/partials/footer.html
{% load static %}

<footer>
	<div class="footer-content">
		<h3>{{ site_name_full|upper }}</h3>
		<p>{{ moto|title }}</p>
		<ul class="socials">
			<li><a href="https://www.facebook.com/107274258794499/posts/1156982825232001/?substory_index=1156982825232001&app=fbl"><i class="fab fa-facebook-f"></i></a></li>
			<li><a href=""><i class="fab fa-twitter"></i></a></li>
			<li><a href=""><i class="fab fa-instagram"></i></a></li>
		</ul>
	</div>
	<div class="footer-bottom">
		<p>{{ site_name_long|title }} &copy;2022. designed by <span>Pyweb</span></p>
	</div>
</footer>

templates/partials/nav.html
{% load static %}
<header>
	<div class="logo">
		<img src="{% static 'css/img/logo.png' %}" alt="">
		<h1 class="logo-title">{{ site_name_short|upper }}</h1>
	</div>
	<input type="checkbox" name="nav-toggle" class="nav-toggle" id="nav-toggle">
	<nav>
		<ul>
			<li><a href="{% url 'home:home' %}">Home</a></li>
			<li><a href="#services">Services</a></li>
			<li><a href="#about">About</a></li>
			<li><a href="#contact">Contact</a></li>
		</ul>
	</nav>
	<label for="nav-toggle" class="nav-toggle-label">
		<span></span>
	</label>
</header>

templates/partials/scripts.html
{% load static %}

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'assets/js/isotope.min.js' %}"></script>
<script src="{% static 'assets/js/owl-carousel.js' %}"></script>
<script src="{% static 'assets/js/lightbox.js' %}"></script>
<script src="{% static 'assets/js/tabs.js' %}"></script>
<script src="{% static 'assets/js/video.js' %}"></script>
<script src="{% static 'assets/js/slick-slider.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<script>
    //according to loftblog tut
    $('.nav li:first').addClass('active');

    var showSection = function showSection(section, isAnimate) {
      var
      direction = section.replace(/#/, ''),
      reqSection = $('.section').filter('[data-section="' + direction + '"]'),
      reqSectionPos = reqSection.offset().top - 0;

      if (isAnimate) {
        $('body, html').animate({
          scrollTop: reqSectionPos },
        800);
      } else {
        $('body, html').scrollTop(reqSectionPos);
      }

    };

    var checkSection = function checkSection() {
      $('.section').each(function () {
        var
        $this = $(this),
        topEdge = $this.offset().top - 80,
        bottomEdge = topEdge + $this.height(),
        wScroll = $(window).scrollTop();
        if (topEdge < wScroll && bottomEdge > wScroll) {
          var
          currentId = $this.data('section'),
          reqLink = $('a').filter('[href*=\\#' + currentId + ']');
          reqLink.closest('li').addClass('active').
          siblings().removeClass('active');
        }
      });
    };

    $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
      e.preventDefault();
      showSection($(this).attr('href'), true);
    });

    $(window).scroll(function () {
      checkSection();
    });
</script>

templates/partials/team.html
{% load static %}

<section class="wrapper" id="team">
	<h1>our team</h1>
	<div class="team">
		
		{% for member in members %}
		<div class="team-member">
			<div class="team-image">
				<img src="{{ member.avatar.url }}" alt="team-image">
			</div>
			<h3>{{ member.user.username|title }}</h3>
			<p class="role">{{ member.role|title }}</p>
			<p><span>Call</span> +{{ member.mobile }}</p>
			<p><span>whatsapp</span> +{{ member.whatsapp }}</p>

		</div>
		{% endfor %}
	</div>
</section>

templates/partials/testimonials.html
{% load static %}

<section class="t-container" id="testimonials">
	<h1>testimonials</h1>
	<div class="carousel">
		<input type="radio" name="slide" id="indicator1">
		<input type="radio" name="slide" id="indicator2">
		<input type="radio" name="slide" id="indicator3">
		

		<div class="carousel-inner">
			
			{% for review in reviews %}
			<div class="carousel-item">
				<div class="carousel-caption">
					<img src="{{ review.image.url }}" alt="image">
					<h2>{{ review.name|title }} <br><span class="job-title">{{ review.job_description.title }}</span></h2>
					<p>{{ review.review|capfirst }}</p>
				</div>
			</div>
			{% endfor %}
		</div>
		<div class="indicators">
			<label for="indicator1"></label>
			<label for="indicator2"></label>
			<label for="indicator3"></label>
		</div>
	</div>
	<div class="review">
		<a href="{% url 'home:review' %}">Review Us</a>
	</div>
</section>